spring:
  #AppName
  application:
    name: ApplicationName

  #database
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:13306/master
      username: root
      password: 1234
    slave1:
      jdbc-url: jdbc:mysql://localhost:13307/slave1
      username: root
      password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  #jpa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    generate-ddl: true

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace