version: '3'
services:
  mysql_master:
    image: mysql:8.0.21
    volumes:
      - ./mysql_db/master:/mysql
      - ./test_db:/test_db
      - ./db/conf/master/my.cnf:/etc/my.cnf
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./logs:/var/log/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    ports:
      - "31001:3306"

  mysql_slave:
    image: mysql:8.0.21
    volumes:
      - ./mysql_db/slave:/mysql
      - ./test_db:/test_db
      - ./db/conf/slave/my.cnf:/etc/my.cnf
      - ./seeding.sh:/docker-entrypoint-initdb.d/seeding.sh
      - ./logs:/var/log/mysql
    depends_on:
      - mysql_master
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    ports:
      - "31002:3306"