spring:
  application:
    name: CRUDApplication
  datasource:
    url: jdbc:h2:tcp://localhost/~/devdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        default_batch_fetch_size: 1000
    generate-ddl: true


logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace