spring:
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true

    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop