spring:
  datasource:
    url: jdbc:mysql://localhost:13306/devdb
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true

    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  data:
    elasticsearch:
      repositories:
        enabled: true