spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    generate-ddl: true
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:31001/test_db
      username: app_user
      password: 1234
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:31002/test_db
      username: app_user
      password: 1234