spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cachedb
    username: root
    password: gmltmd75
    driver-class-name: com.mysql.cj.jdbc.Driver
  #
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  redis:
    host: localhost
    port: 6379


logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace