version: '3'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=devdb
      - MYSQL_ROOT_HOST=%
