DROP DATABASE IF EXISTS test_db;

CREATE DATABASE test_db DEFAULT CHARSET utf8mb4;

USE test_db;
SET sql_mode = '';

DROP TABLE if EXISTS LONGMAIL_INTERFACE;
CREATE TABLE `MAIL_INTERFACE` (
  `SEQ` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(100) DEFAULT NULL,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `SERVICE_NAME` VARCHAR(45) DEFAULT NULL,
  `SENTTIME` DATETIME DEFAULT NULL,
  `SENDYN` CHAR(1) DEFAULT 'N',
  PRIMARY KEY (`SEQ`),
  KEY `idx_MAIL_INTERFACE_1` (`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;